"""init db

Revision ID: 33ac85f12b42
Revises: 
Create Date: 2020-02-14 18:27:14.382853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ac85f12b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('wikidata_parent_entity', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('external_id', sa.BIGINT(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_backend'), 'users', ['backend'], unique=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('initiator_id', sa.BIGINT(), nullable=True),
    sa.Column('participant_id', sa.BIGINT(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_backend'), 'games', ['backend'], unique=False)
    op.create_index(op.f('ix_games_room_id'), 'games', ['room_id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name'),
    sa.UniqueConstraint('category_id', 'wikidata_id')
    )
    op.create_table('question_types',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('text_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('image_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('sound_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('coords_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('is_question_in_child', sa.String(), nullable=True),
    sa.Column('child_prop', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_aliases',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('object_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('ask_date', sa.DateTime(), nullable=True),
    sa.Column('right_answers', sa.JSON(), nullable=True),
    sa.Column('associated_user_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['associated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_ask_date'), 'questions', ['ask_date'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_ask_date'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('object_aliases')
    op.drop_table('question_types')
    op.drop_table('objects')
    op.drop_index(op.f('ix_games_room_id'), table_name='games')
    op.drop_index(op.f('ix_games_backend'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_backend'), table_name='users')
    op.drop_table('users')
    op.drop_table('object_categories')
    # ### end Alembic commands ###
