"""auto

Revision ID: be8d9790bbe8
Revises: 
Create Date: 2020-02-09 15:40:05.027414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8d9790bbe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikidata_parent_entity', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('initiator_id', sa.BIGINT(), nullable=True),
    sa.Column('participant_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name'),
    sa.UniqueConstraint('category_id', 'wikidata_id')
    )
    op.create_table('question_types',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('text_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('image_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('sound_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('coords_question_wikidata_prop', sa.String(), nullable=True),
    sa.Column('is_question_in_child', sa.String(), nullable=True),
    sa.Column('child_prop', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_aliases',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('object_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.Column('right_object_id', sa.Integer(), nullable=True),
    sa.Column('associated_user_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['associated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['right_object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('object_aliases')
    op.drop_table('question_types')
    op.drop_table('objects')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('object_categories')
    # ### end Alembic commands ###
