version: '3'
services:
  postgres:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - wdquiznetwork
    environment:
      - POSTGRES_DB=wdquizdb
      - POSTGRES_USER=wdquizdbuser
      - POSTGRES_PASSWORD=wdquizdbpassword

  app:
    build: .
    command: bash -c 'alembic upgrade head && python -m flask run -h 0.0.0.0'
    volumes:
      - .:/app
      - ./media:/app/media
      - ./.bash_history:/root/.bash_history
    depends_on:
      - postgres
    networks:
      - wdquiznetwork
    environment:
      - IPYTHONDIR=/app/.ipython
    env_file:
      - .env

  nginx:
    build: ./nginx
    depends_on:
      - app
    volumes:
      - ./media/:/app/media
    links:
      - frontend
      - app
    ports:
      - 80:80
    networks:
      - wdquiznetwork

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    environment:
      - APP_ENV=dev
    depends_on:
      - app
    networks:
      - wdquiznetwork
    volumes:
      - ./frontend:/app/src

volumes:
  postgres_data:


networks:
  wdquiznetwork:
    driver: bridge
