version: '3'
services:
  postgres:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5439:5432
    environment:
      - POSTGRES_DB=wdquizdb
      - POSTGRES_USER=wdquizdbuser
      - POSTGRES_PASSWORD=wdquizdbpassword
  app:
    build: .
    command: bash -c 'alembic upgrade head && python -m flask run -h 0.0.0.0'
    volumes:
      - .:/app
      - ./media:/app/media
      - ./.bash_history:/root/.bash_history
    depends_on:
      - postgres
    environment:
      - IPYTHONDIR=/app/.ipython
    env_file:
      - .env
    ports:
      - 5000:5000

  nginx:
    build: ./nginx
    depends_on:
      - app
    volumes:
      - ./media/:/app/media
    ports:
      - 80:80

volumes:
  postgres_data:
